/*
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import uk.ac.ox.cs.xdrone.ui.internal.XdroneActivator;

public class XDroneUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XdroneActivator.getInstance().getInjector("uk.ac.ox.cs.xdrone.XDrone");
	}

}
