/*
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXDroneScopeProvider extends DelegatingScopeProvider {
}
