/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.scoping;

import uk.ac.ox.cs.xdrone.scoping.AbstractXDroneScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XDroneScopeProvider extends AbstractXDroneScopeProvider {
}
