/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.serializer;

import uk.ac.ox.cs.xdrone.serializer.AbstractXDroneSyntacticSequencer;

@SuppressWarnings("all")
public class XDroneSyntacticSequencer extends AbstractXDroneSyntacticSequencer {
}
