/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.binder.AnnotatedBindingBuilder;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.web.server.XtextServiceDispatcher;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;
import uk.ac.ox.cs.xdrone.web.AbstractXDroneWebModule;
import uk.ac.ox.cs.xdrone.web.XDroneResourceHandler;
import uk.ac.ox.cs.xdrone.web.XDroneServiceDispatcher;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XDroneWebModule extends AbstractXDroneWebModule {
  public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
    return XDroneResourceHandler.class;
  }
  
  public Class<? extends XtextServiceDispatcher> bindXtextServiceDispatcher() {
    return XDroneServiceDispatcher.class;
  }
  
  public void configureIResourceBaseProvider(final Binder binder) {
    AnnotatedBindingBuilder<IResourceBaseProvider> _bind = binder.<IResourceBaseProvider>bind(IResourceBaseProvider.class);
    ResourceBaseProviderImpl _resourceBaseProviderImpl = new ResourceBaseProviderImpl("./booster-files");
    _bind.toInstance(_resourceBaseProviderImpl);
  }
  
  public XDroneWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
