/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.ox.cs.xdrone.web.AbstractXDroneWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XDroneWebModule extends AbstractXDroneWebModule {
  public XDroneWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
