/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.ox.cs.xdrone.XDroneRuntimeModule;
import uk.ac.ox.cs.xdrone.XDroneStandaloneSetup;
import uk.ac.ox.cs.xdrone.web.XDroneWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XDroneWebSetup extends XDroneStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final XDroneRuntimeModule runtimeModule = new XDroneRuntimeModule();
    final XDroneWebModule webModule = new XDroneWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public XDroneWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
