/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import uk.ac.ox.cs.xdrone.services.XDroneGrammarAccess;
import uk.ac.ox.cs.xdrone.xDrone.Main;
import uk.ac.ox.cs.xdrone.xDrone.Program;

@SuppressWarnings("all")
public class XDroneFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private XDroneGrammarAccess _xDroneGrammarAccess;
  
  protected void _format(final Program program, @Extension final IFormattableDocument document) {
    Main _main = program.getMain();
    document.<Main>format(_main);
  }
  
  public void format(final Object program, final IFormattableDocument document) {
    if (program instanceof XtextResource) {
      _format((XtextResource)program, document);
      return;
    } else if (program instanceof Program) {
      _format((Program)program, document);
      return;
    } else if (program instanceof EObject) {
      _format((EObject)program, document);
      return;
    } else if (program == null) {
      _format((Void)null, document);
      return;
    } else if (program != null) {
      _format(program, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(program, document).toString());
    }
  }
}
