/*
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uk.ac.ox.cs.xdrone.ui.internal.XdroneActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XDroneExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XdroneActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XdroneActivator.getInstance().getInjector(XdroneActivator.UK_AC_OX_CS_XDRONE_XDRONE);
	}
	
}
