/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone;

import uk.ac.ox.cs.xdrone.AbstractXDroneRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XDroneRuntimeModule extends AbstractXDroneRuntimeModule {
}
