/*
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXDroneValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.ox.cs.xdrone.xDrone.XDronePackage.eINSTANCE);
		return result;
	}
	
}
