/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.ui.contentassist;

import uk.ac.ox.cs.xdrone.ui.contentassist.AbstractXDroneProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XDroneProposalProvider extends AbstractXDroneProposalProvider {
}
