/*
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XDroneAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/ox/cs/xdrone/parser/antlr/internal/InternalXDrone.tokens");
	}
}
