/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterators;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import uk.ac.ox.cs.xdrone.xDrone.Main;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class XDroneGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    String result = "";
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<Main> _filter = Iterators.<Main>filter(_allContents, Main.class);
    boolean _notEquals = (!Objects.equal(_filter, null));
    if (_notEquals) {
      String _result = result;
      result = (_result + "public static void main(String[] args) {}");
    }
    fsa.generateFile("functions.txt", ("Defined functions: " + result));
  }
}
