/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.generator;

import com.google.common.collect.Iterators;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import uk.ac.ox.cs.xdrone.xDrone.Fun;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class XDroneGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<Fun> _filter = Iterators.<Fun>filter(_allContents, Fun.class);
    final Function1<Fun, String> _function = (Fun it) -> {
      return it.getName();
    };
    Iterator<String> _map = IteratorExtensions.<Fun, String>map(_filter, _function);
    String _join = IteratorExtensions.join(_map, ", ");
    String _plus = ("Defined functions: " + _join);
    fsa.generateFile("functions.txt", _plus);
  }
}
