/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterators;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;
import uk.ac.ox.cs.xdrone.xDrone.Main;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class XDroneGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    String result = "";
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<Main> _filter = Iterators.<Main>filter(_allContents, Main.class);
    boolean _notEquals = (!Objects.equal(_filter, null));
    if (_notEquals) {
      String _result = result;
      result = (_result + "public static void main(String[] args) {}");
    }
    try {
      PrintWriter writer = new PrintWriter("/tmp/result567.java", "UTF-8");
      writer.println(result);
      writer.close();
    } catch (final Throwable _t) {
      if (_t instanceof IOException) {
        final IOException e = (IOException)_t;
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
  }
}
