/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.xdrone.xDrone.BlockExpression#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getBlockExpression()
 * @model
 * @generated
 */
public interface BlockExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' attribute list.
   * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getBlockExpression_Expressions()
   * @model unique="false"
   * @generated
   */
  EList<String> getExpressions();

} // BlockExpression
