/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
