/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fun</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getParameters <em>Parameters</em>}</li>
 *   <li>{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getFun()
 * @model
 * @generated
 */
public interface Fun extends Executable
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getFun_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.ox.cs.xdrone.xDrone.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getFun_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(BlockExpression)
   * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getFun_Body()
   * @model containment="true"
   * @generated
   */
  BlockExpression getBody();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(BlockExpression value);

} // Fun
