/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.xdrone.xDrone.Program#getSubPrograms <em>Sub Programs</em>}</li>
 *   <li>{@link uk.ac.ox.cs.xdrone.xDrone.Program#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends Executable
{
  /**
   * Returns the value of the '<em><b>Sub Programs</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.ox.cs.xdrone.xDrone.Fun}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Programs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Programs</em>' containment reference list.
   * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getProgram_SubPrograms()
   * @model containment="true"
   * @generated
   */
  EList<Fun> getSubPrograms();

  /**
   * Returns the value of the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' containment reference.
   * @see #setMain(Main)
   * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getProgram_Main()
   * @model containment="true"
   * @generated
   */
  Main getMain();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.xdrone.xDrone.Program#getMain <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' containment reference.
   * @see #getMain()
   * @generated
   */
  void setMain(Main value);

} // Program
