/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Up</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.ox.cs.xdrone.xDrone.XDronePackage#getUp()
 * @model
 * @generated
 */
public interface Up extends Command
{
} // Up
