/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.ox.cs.xdrone.xDrone.XDroneFactory
 * @model kind="package"
 * @generated
 */
public interface XDronePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xDrone";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/ox/cs/xdrone/XDrone";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xDrone";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XDronePackage eINSTANCE = uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MAIN = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMain()
   * @generated
   */
  int MAIN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 2;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__MILLISECONDS = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.UpImpl <em>Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.UpImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getUp()
   * @generated
   */
  int UP = 3;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.DownImpl <em>Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.DownImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getDown()
   * @generated
   */
  int DOWN = 4;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.LeftImpl <em>Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.LeftImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getLeft()
   * @generated
   */
  int LEFT = 5;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RightImpl <em>Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.RightImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRight()
   * @generated
   */
  int RIGHT = 6;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ForwardImpl <em>Forward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ForwardImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getForward()
   * @generated
   */
  int FORWARD = 7;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Forward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.BackwardImpl <em>Backward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.BackwardImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getBackward()
   * @generated
   */
  int BACKWARD = 8;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Backward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RotateLImpl <em>Rotate L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.RotateLImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRotateL()
   * @generated
   */
  int ROTATE_L = 9;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Rotate L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RotateRImpl <em>Rotate R</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.RotateRImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRotateR()
   * @generated
   */
  int ROTATE_R = 10;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R__MILLISECONDS = COMMAND__MILLISECONDS;

  /**
   * The number of structural features of the '<em>Rotate R</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Program#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program#getMain()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Main();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getName()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getCommands()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Commands();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Command#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Command#getMilliseconds()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Up <em>Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Up</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Up
   * @generated
   */
  EClass getUp();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Down <em>Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Down</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Down
   * @generated
   */
  EClass getDown();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Left <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Left
   * @generated
   */
  EClass getLeft();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Right <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Right
   * @generated
   */
  EClass getRight();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Forward <em>Forward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forward</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Forward
   * @generated
   */
  EClass getForward();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Backward <em>Backward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backward</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Backward
   * @generated
   */
  EClass getBackward();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.RotateL <em>Rotate L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate L</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.RotateL
   * @generated
   */
  EClass getRotateL();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.RotateR <em>Rotate R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate R</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.RotateR
   * @generated
   */
  EClass getRotateR();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XDroneFactory getXDroneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MAIN = eINSTANCE.getProgram_Main();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__NAME = eINSTANCE.getMain_Name();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__COMMANDS = eINSTANCE.getMain_Commands();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__MILLISECONDS = eINSTANCE.getCommand_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.UpImpl <em>Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.UpImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getUp()
     * @generated
     */
    EClass UP = eINSTANCE.getUp();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.DownImpl <em>Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.DownImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getDown()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDown();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.LeftImpl <em>Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.LeftImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getLeft()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLeft();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RightImpl <em>Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.RightImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRight()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRight();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ForwardImpl <em>Forward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ForwardImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getForward()
     * @generated
     */
    EClass FORWARD = eINSTANCE.getForward();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.BackwardImpl <em>Backward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.BackwardImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getBackward()
     * @generated
     */
    EClass BACKWARD = eINSTANCE.getBackward();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RotateLImpl <em>Rotate L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.RotateLImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRotateL()
     * @generated
     */
    EClass ROTATE_L = eINSTANCE.getRotateL();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RotateRImpl <em>Rotate R</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.RotateRImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRotateR()
     * @generated
     */
    EClass ROTATE_R = eINSTANCE.getRotateR();

  }

} //XDronePackage
