/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.ox.cs.xdrone.xDrone.XDroneFactory
 * @model kind="package"
 * @generated
 */
public interface XDronePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xDrone";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/ox/cs/xdrone/XDrone";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xDrone";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XDronePackage eINSTANCE = uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ExecutableImpl <em>Executable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ExecutableImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getExecutable()
   * @generated
   */
  int EXECUTABLE = 5;

  /**
   * The number of structural features of the '<em>Executable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Sub Programs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__SUB_PROGRAMS = EXECUTABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MAIN = EXECUTABLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = EXECUTABLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.FunImpl <em>Fun</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.FunImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getFun()
   * @generated
   */
  int FUN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__NAME = EXECUTABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__PARAMETERS = EXECUTABLE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__BODY = EXECUTABLE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fun</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN_FEATURE_COUNT = EXECUTABLE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ParameterImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMain()
   * @generated
   */
  int MAIN = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Commands</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__COMMANDS = 2;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.BlockExpressionImpl <em>Block Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.BlockExpressionImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getBlockExpression()
   * @generated
   */
  int BLOCK_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Commands</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_EXPRESSION__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Block Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ExpressionImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.NumberImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.AdditionImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.MultiplicationImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.xdrone.xDrone.Program#getSubPrograms <em>Sub Programs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Programs</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program#getSubPrograms()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_SubPrograms();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Program#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program#getMain()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Main();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Fun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fun</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Fun
   * @generated
   */
  EClass getFun();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Fun#getName()
   * @see #getFun()
   * @generated
   */
  EAttribute getFun_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Fun#getParameters()
   * @see #getFun()
   * @generated
   */
  EReference getFun_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Fun#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Fun#getBody()
   * @see #getFun()
   * @generated
   */
  EReference getFun_Body();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Type();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getName()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getParameters()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Parameters();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Commands</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getCommands()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Commands();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.BlockExpression <em>Block Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block Expression</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.BlockExpression
   * @generated
   */
  EClass getBlockExpression();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.ox.cs.xdrone.xDrone.BlockExpression#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Commands</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.BlockExpression#getCommands()
   * @see #getBlockExpression()
   * @generated
   */
  EAttribute getBlockExpression_Commands();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Executable <em>Executable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Executable</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Executable
   * @generated
   */
  EClass getExecutable();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Number#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Number#getValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XDroneFactory getXDroneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Sub Programs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__SUB_PROGRAMS = eINSTANCE.getProgram_SubPrograms();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MAIN = eINSTANCE.getProgram_Main();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.FunImpl <em>Fun</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.FunImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getFun()
     * @generated
     */
    EClass FUN = eINSTANCE.getFun();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUN__NAME = eINSTANCE.getFun_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__PARAMETERS = eINSTANCE.getFun_Parameters();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__BODY = eINSTANCE.getFun_Body();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ParameterImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__NAME = eINSTANCE.getMain_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__PARAMETERS = eINSTANCE.getMain_Parameters();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__COMMANDS = eINSTANCE.getMain_Commands();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.BlockExpressionImpl <em>Block Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.BlockExpressionImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getBlockExpression()
     * @generated
     */
    EClass BLOCK_EXPRESSION = eINSTANCE.getBlockExpression();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCK_EXPRESSION__COMMANDS = eINSTANCE.getBlockExpression_Commands();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ExecutableImpl <em>Executable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ExecutableImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getExecutable()
     * @generated
     */
    EClass EXECUTABLE = eINSTANCE.getExecutable();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ExpressionImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.NumberImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__VALUE = eINSTANCE.getNumber_Value();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.AdditionImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.MultiplicationImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

  }

} //XDronePackage
