/**
 * generated by Xtext 2.10.0
 */
package uk.ac.ox.cs.xdrone.xDrone;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.ox.cs.xdrone.xDrone.XDroneFactory
 * @model kind="package"
 * @generated
 */
public interface XDronePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xDrone";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/ox/cs/xdrone/XDrone";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xDrone";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XDronePackage eINSTANCE = uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MAIN = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMain()
   * @generated
   */
  int MAIN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 2;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.UPImpl <em>UP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.UPImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getUP()
   * @generated
   */
  int UP = 3;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>UP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.DOWNImpl <em>DOWN</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.DOWNImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getDOWN()
   * @generated
   */
  int DOWN = 4;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>DOWN</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.LEFTImpl <em>LEFT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.LEFTImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getLEFT()
   * @generated
   */
  int LEFT = 5;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>LEFT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RIGHTImpl <em>RIGHT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.RIGHTImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRIGHT()
   * @generated
   */
  int RIGHT = 6;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RIGHT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.FORWARDImpl <em>FORWARD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.FORWARDImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getFORWARD()
   * @generated
   */
  int FORWARD = 7;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>FORWARD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.BACKWARDImpl <em>BACKWARD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.BACKWARDImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getBACKWARD()
   * @generated
   */
  int BACKWARD = 8;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>BACKWARD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ROTATEImpl <em>ROTATE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.ROTATEImpl
   * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getROTATE()
   * @generated
   */
  int ROTATE = 9;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE__DEGREES = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ROTATE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.xdrone.xDrone.Program#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Program#getMain()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Main();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getName()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.xdrone.xDrone.Main#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Main#getCommands()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Commands();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.UP <em>UP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>UP</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.UP
   * @generated
   */
  EClass getUP();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.UP#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.UP#getMilliseconds()
   * @see #getUP()
   * @generated
   */
  EAttribute getUP_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.DOWN <em>DOWN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DOWN</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.DOWN
   * @generated
   */
  EClass getDOWN();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.DOWN#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.DOWN#getMilliseconds()
   * @see #getDOWN()
   * @generated
   */
  EAttribute getDOWN_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.LEFT <em>LEFT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LEFT</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.LEFT
   * @generated
   */
  EClass getLEFT();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.LEFT#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.LEFT#getMilliseconds()
   * @see #getLEFT()
   * @generated
   */
  EAttribute getLEFT_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.RIGHT <em>RIGHT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RIGHT</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.RIGHT
   * @generated
   */
  EClass getRIGHT();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.RIGHT#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.RIGHT#getMilliseconds()
   * @see #getRIGHT()
   * @generated
   */
  EAttribute getRIGHT_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.FORWARD <em>FORWARD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FORWARD</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.FORWARD
   * @generated
   */
  EClass getFORWARD();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.FORWARD#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.FORWARD#getMilliseconds()
   * @see #getFORWARD()
   * @generated
   */
  EAttribute getFORWARD_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.BACKWARD <em>BACKWARD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BACKWARD</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.BACKWARD
   * @generated
   */
  EClass getBACKWARD();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.BACKWARD#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.BACKWARD#getMilliseconds()
   * @see #getBACKWARD()
   * @generated
   */
  EAttribute getBACKWARD_Milliseconds();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.xdrone.xDrone.ROTATE <em>ROTATE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ROTATE</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.ROTATE
   * @generated
   */
  EClass getROTATE();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.xdrone.xDrone.ROTATE#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degrees</em>'.
   * @see uk.ac.ox.cs.xdrone.xDrone.ROTATE#getDegrees()
   * @see #getROTATE()
   * @generated
   */
  EAttribute getROTATE_Degrees();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XDroneFactory getXDroneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ProgramImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MAIN = eINSTANCE.getProgram_Main();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.MainImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__NAME = eINSTANCE.getMain_Name();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__COMMANDS = eINSTANCE.getMain_Commands();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.CommandImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.UPImpl <em>UP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.UPImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getUP()
     * @generated
     */
    EClass UP = eINSTANCE.getUP();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UP__MILLISECONDS = eINSTANCE.getUP_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.DOWNImpl <em>DOWN</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.DOWNImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getDOWN()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDOWN();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOWN__MILLISECONDS = eINSTANCE.getDOWN_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.LEFTImpl <em>LEFT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.LEFTImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getLEFT()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLEFT();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEFT__MILLISECONDS = eINSTANCE.getLEFT_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.RIGHTImpl <em>RIGHT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.RIGHTImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getRIGHT()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRIGHT();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGHT__MILLISECONDS = eINSTANCE.getRIGHT_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.FORWARDImpl <em>FORWARD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.FORWARDImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getFORWARD()
     * @generated
     */
    EClass FORWARD = eINSTANCE.getFORWARD();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORWARD__MILLISECONDS = eINSTANCE.getFORWARD_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.BACKWARDImpl <em>BACKWARD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.BACKWARDImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getBACKWARD()
     * @generated
     */
    EClass BACKWARD = eINSTANCE.getBACKWARD();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKWARD__MILLISECONDS = eINSTANCE.getBACKWARD_Milliseconds();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.xdrone.xDrone.impl.ROTATEImpl <em>ROTATE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.ROTATEImpl
     * @see uk.ac.ox.cs.xdrone.xDrone.impl.XDronePackageImpl#getROTATE()
     * @generated
     */
    EClass ROTATE = eINSTANCE.getROTATE();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE__DEGREES = eINSTANCE.getROTATE_Degrees();

  }

} //XDronePackage
